// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHBqaor-GkbPG5oymTlroA6l1NICxp_W4',
    appId: '1:294779660954:web:98d5cd5a9f1f2565abcd23',
    messagingSenderId: '294779660954',
    projectId: 'assignment-10-12888',
    authDomain: 'assignment-10-12888.firebaseapp.com',
    storageBucket: 'assignment-10-12888.appspot.com',
    measurementId: 'G-L72M38FES0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDNyhrcpLY5xdKU-hOyxKsnm-AWcqsw40',
    appId: '1:294779660954:android:bd694ea184909999abcd23',
    messagingSenderId: '294779660954',
    projectId: 'assignment-10-12888',
    storageBucket: 'assignment-10-12888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSc0AxuiKZ3KwgP7Wf29jE2xG2utfzD8Y',
    appId: '1:294779660954:ios:7957bc0caeaedb2dabcd23',
    messagingSenderId: '294779660954',
    projectId: 'assignment-10-12888',
    storageBucket: 'assignment-10-12888.appspot.com',
    iosBundleId: 'com.example.rPlace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSc0AxuiKZ3KwgP7Wf29jE2xG2utfzD8Y',
    appId: '1:294779660954:ios:7957bc0caeaedb2dabcd23',
    messagingSenderId: '294779660954',
    projectId: 'assignment-10-12888',
    storageBucket: 'assignment-10-12888.appspot.com',
    iosBundleId: 'com.example.rPlace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHBqaor-GkbPG5oymTlroA6l1NICxp_W4',
    appId: '1:294779660954:web:2e7bfbbc2e7f9d96abcd23',
    messagingSenderId: '294779660954',
    projectId: 'assignment-10-12888',
    authDomain: 'assignment-10-12888.firebaseapp.com',
    storageBucket: 'assignment-10-12888.appspot.com',
    measurementId: 'G-3JQGTGG6S6',
  );
}
